// Code generated by MockGen. DO NOT EDIT.
// Source: ../source.go
//
// Generated by this command:
//
//	mockgen -source=../source.go -destination=source.go -package=mock_ssh_agent_source_repo
//

// Package mock_ssh_agent_source_repo is a generated GoMock package.
package mock_ssh_agent_source_repo

import (
	context "context"
	reflect "reflect"

	ssh_agent_source_entity "github.com/opskat/opskat/internal/model/entity/ssh_agent_source_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSSHAgentSourceRepo is a mock of SSHAgentSourceRepo interface.
type MockSSHAgentSourceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSSHAgentSourceRepoMockRecorder
	isgomock struct{}
}

// MockSSHAgentSourceRepoMockRecorder is the mock recorder for MockSSHAgentSourceRepo.
type MockSSHAgentSourceRepoMockRecorder struct {
	mock *MockSSHAgentSourceRepo
}

// NewMockSSHAgentSourceRepo creates a new mock instance.
func NewMockSSHAgentSourceRepo(ctrl *gomock.Controller) *MockSSHAgentSourceRepo {
	mock := &MockSSHAgentSourceRepo{ctrl: ctrl}
	mock.recorder = &MockSSHAgentSourceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSHAgentSourceRepo) EXPECT() *MockSSHAgentSourceRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSSHAgentSourceRepo) Create(ctx context.Context, src *ssh_agent_source_entity.SSHAgentSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSSHAgentSourceRepoMockRecorder) Create(ctx, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSSHAgentSourceRepo)(nil).Create), ctx, src)
}

// Delete mocks base method.
func (m *MockSSHAgentSourceRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSSHAgentSourceRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSSHAgentSourceRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockSSHAgentSourceRepo) Find(ctx context.Context, id int64) (*ssh_agent_source_entity.SSHAgentSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*ssh_agent_source_entity.SSHAgentSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSSHAgentSourceRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSSHAgentSourceRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockSSHAgentSourceRepo) List(ctx context.Context) ([]*ssh_agent_source_entity.SSHAgentSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*ssh_agent_source_entity.SSHAgentSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSSHAgentSourceRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSSHAgentSourceRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockSSHAgentSourceRepo) Update(ctx context.Context, src *ssh_agent_source_entity.SSHAgentSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSSHAgentSourceRepoMockRecorder) Update(ctx, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSSHAgentSourceRepo)(nil).Update), ctx, src)
}
