// Code generated by MockGen. DO NOT EDIT.
// Source: custom_type.go
//
// Generated by this command:
//
//	mockgen -source=custom_type.go -destination=mock_custom_type_repo/custom_type.go -package=mock_custom_type_repo
//

// Package mock_custom_type_repo is a generated GoMock package.
package mock_custom_type_repo

import (
	context "context"
	reflect "reflect"

	custom_type_entity "github.com/opskat/opskat/internal/model/entity/custom_type_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomTypeRepo is a mock of CustomTypeRepo interface.
type MockCustomTypeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCustomTypeRepoMockRecorder
	isgomock struct{}
}

// MockCustomTypeRepoMockRecorder is the mock recorder for MockCustomTypeRepo.
type MockCustomTypeRepoMockRecorder struct {
	mock *MockCustomTypeRepo
}

// NewMockCustomTypeRepo creates a new mock instance.
func NewMockCustomTypeRepo(ctrl *gomock.Controller) *MockCustomTypeRepo {
	mock := &MockCustomTypeRepo{ctrl: ctrl}
	mock.recorder = &MockCustomTypeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomTypeRepo) EXPECT() *MockCustomTypeRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomTypeRepo) Create(ctx context.Context, ct *custom_type_entity.CustomType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ct)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCustomTypeRepoMockRecorder) Create(ctx, ct any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomTypeRepo)(nil).Create), ctx, ct)
}

// Delete mocks base method.
func (m *MockCustomTypeRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomTypeRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomTypeRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockCustomTypeRepo) Find(ctx context.Context, id int64) (*custom_type_entity.CustomType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*custom_type_entity.CustomType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCustomTypeRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCustomTypeRepo)(nil).Find), ctx, id)
}

// FindBySlug mocks base method.
func (m *MockCustomTypeRepo) FindBySlug(ctx context.Context, slug string) (*custom_type_entity.CustomType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*custom_type_entity.CustomType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockCustomTypeRepoMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockCustomTypeRepo)(nil).FindBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockCustomTypeRepo) List(ctx context.Context) ([]*custom_type_entity.CustomType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*custom_type_entity.CustomType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCustomTypeRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCustomTypeRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockCustomTypeRepo) Update(ctx context.Context, ct *custom_type_entity.CustomType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ct)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomTypeRepoMockRecorder) Update(ctx, ct any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomTypeRepo)(nil).Update), ctx, ct)
}
