// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/codfrm/Code/ops-cat/internal/repository/asset_repo/asset.go
//
// Generated by this command:
//
//	mockgen -source=/Users/codfrm/Code/ops-cat/internal/repository/asset_repo/asset.go -destination=/Users/codfrm/Code/ops-cat/internal/repository/asset_repo/mock_asset_repo/asset.go -package=mock_asset_repo
//

// Package mock_asset_repo is a generated GoMock package.
package mock_asset_repo

import (
	context "context"
	asset_entity "ops-cat/internal/model/entity/asset_entity"
	asset_repo "ops-cat/internal/repository/asset_repo"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAssetRepo is a mock of AssetRepo interface.
type MockAssetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAssetRepoMockRecorder
	isgomock struct{}
}

// MockAssetRepoMockRecorder is the mock recorder for MockAssetRepo.
type MockAssetRepoMockRecorder struct {
	mock *MockAssetRepo
}

// NewMockAssetRepo creates a new mock instance.
func NewMockAssetRepo(ctrl *gomock.Controller) *MockAssetRepo {
	mock := &MockAssetRepo{ctrl: ctrl}
	mock.recorder = &MockAssetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetRepo) EXPECT() *MockAssetRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAssetRepo) Create(ctx context.Context, asset *asset_entity.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAssetRepoMockRecorder) Create(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAssetRepo)(nil).Create), ctx, asset)
}

// Delete mocks base method.
func (m *MockAssetRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAssetRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAssetRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockAssetRepo) Find(ctx context.Context, id int64) (*asset_entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*asset_entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAssetRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAssetRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockAssetRepo) List(ctx context.Context, opts asset_repo.ListOptions) ([]*asset_entity.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*asset_entity.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAssetRepoMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAssetRepo)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockAssetRepo) Update(ctx context.Context, asset *asset_entity.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAssetRepoMockRecorder) Update(ctx, asset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAssetRepo)(nil).Update), ctx, asset)
}
