// Code generated by MockGen. DO NOT EDIT.
// Source: command_review.go
//
// Generated by this command:
//
//	mockgen -source=command_review.go -destination=mock_command_review_repo/command_review.go -package=mock_command_review_repo
//

// Package mock_command_review_repo is a generated GoMock package.
package mock_command_review_repo

import (
	context "context"
	reflect "reflect"

	command_review_entity "github.com/opskat/opskat/internal/model/entity/command_review_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandReviewRepo is a mock of CommandReviewRepo interface.
type MockCommandReviewRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCommandReviewRepoMockRecorder
	isgomock struct{}
}

// MockCommandReviewRepoMockRecorder is the mock recorder for MockCommandReviewRepo.
type MockCommandReviewRepoMockRecorder struct {
	mock *MockCommandReviewRepo
}

// NewMockCommandReviewRepo creates a new mock instance.
func NewMockCommandReviewRepo(ctrl *gomock.Controller) *MockCommandReviewRepo {
	mock := &MockCommandReviewRepo{ctrl: ctrl}
	mock.recorder = &MockCommandReviewRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandReviewRepo) EXPECT() *MockCommandReviewRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCommandReviewRepo) Get(ctx context.Context, cacheKey string, now int64) (*command_review_entity.CommandReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, cacheKey, now)
	ret0, _ := ret[0].(*command_review_entity.CommandReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommandReviewRepoMockRecorder) Get(ctx, cacheKey, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommandReviewRepo)(nil).Get), ctx, cacheKey, now)
}

// Put mocks base method.
func (m *MockCommandReviewRepo) Put(ctx context.Context, r *command_review_entity.CommandReview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockCommandReviewRepoMockRecorder) Put(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockCommandReviewRepo)(nil).Put), ctx, r)
}
