// Code generated by MockGen. DO NOT EDIT.
// Source: snippet.go
//
// Generated by this command:
//
//	mockgen -source=snippet.go -destination=mock_snippet_repo/snippet.go -package=mock_snippet_repo
//

// Package mock_snippet_repo is a generated GoMock package.
package mock_snippet_repo

import (
	context "context"
	reflect "reflect"

	snippet_entity "github.com/opskat/opskat/internal/model/entity/snippet_entity"
	snippet_repo "github.com/opskat/opskat/internal/repository/snippet_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockSnippetRepo is a mock of SnippetRepo interface.
type MockSnippetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSnippetRepoMockRecorder
	isgomock struct{}
}

// MockSnippetRepoMockRecorder is the mock recorder for MockSnippetRepo.
type MockSnippetRepoMockRecorder struct {
	mock *MockSnippetRepo
}

// NewMockSnippetRepo creates a new mock instance.
func NewMockSnippetRepo(ctrl *gomock.Controller) *MockSnippetRepo {
	mock := &MockSnippetRepo{ctrl: ctrl}
	mock.recorder = &MockSnippetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnippetRepo) EXPECT() *MockSnippetRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSnippetRepo) Create(ctx context.Context, s *snippet_entity.Snippet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSnippetRepoMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSnippetRepo)(nil).Create), ctx, s)
}

// DeleteExtensionSeedsMissing mocks base method.
func (m *MockSnippetRepo) DeleteExtensionSeedsMissing(ctx context.Context, source string, keepRefs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExtensionSeedsMissing", ctx, source, keepRefs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExtensionSeedsMissing indicates an expected call of DeleteExtensionSeedsMissing.
func (mr *MockSnippetRepoMockRecorder) DeleteExtensionSeedsMissing(ctx, source, keepRefs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExtensionSeedsMissing", reflect.TypeOf((*MockSnippetRepo)(nil).DeleteExtensionSeedsMissing), ctx, source, keepRefs)
}

// Find mocks base method.
func (m *MockSnippetRepo) Find(ctx context.Context, q snippet_repo.SnippetQuery) ([]*snippet_entity.Snippet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, q)
	ret0, _ := ret[0].([]*snippet_entity.Snippet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSnippetRepoMockRecorder) Find(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSnippetRepo)(nil).Find), ctx, q)
}

// FindBySourceRef mocks base method.
func (m *MockSnippetRepo) FindBySourceRef(ctx context.Context, source, ref string) (*snippet_entity.Snippet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySourceRef", ctx, source, ref)
	ret0, _ := ret[0].(*snippet_entity.Snippet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySourceRef indicates an expected call of FindBySourceRef.
func (mr *MockSnippetRepoMockRecorder) FindBySourceRef(ctx, source, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySourceRef", reflect.TypeOf((*MockSnippetRepo)(nil).FindBySourceRef), ctx, source, ref)
}

// GetByID mocks base method.
func (m *MockSnippetRepo) GetByID(ctx context.Context, id int64) (*snippet_entity.Snippet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*snippet_entity.Snippet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSnippetRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSnippetRepo)(nil).GetByID), ctx, id)
}

// HardDeleteBySource mocks base method.
func (m *MockSnippetRepo) HardDeleteBySource(ctx context.Context, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteBySource", ctx, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteBySource indicates an expected call of HardDeleteBySource.
func (mr *MockSnippetRepoMockRecorder) HardDeleteBySource(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteBySource", reflect.TypeOf((*MockSnippetRepo)(nil).HardDeleteBySource), ctx, source)
}

// SetLastAssets mocks base method.
func (m *MockSnippetRepo) SetLastAssets(ctx context.Context, id int64, assetIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastAssets", ctx, id, assetIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastAssets indicates an expected call of SetLastAssets.
func (mr *MockSnippetRepoMockRecorder) SetLastAssets(ctx, id, assetIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastAssets", reflect.TypeOf((*MockSnippetRepo)(nil).SetLastAssets), ctx, id, assetIDs)
}

// SoftDelete mocks base method.
func (m *MockSnippetRepo) SoftDelete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockSnippetRepoMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockSnippetRepo)(nil).SoftDelete), ctx, id)
}

// TouchUsage mocks base method.
func (m *MockSnippetRepo) TouchUsage(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchUsage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchUsage indicates an expected call of TouchUsage.
func (mr *MockSnippetRepoMockRecorder) TouchUsage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchUsage", reflect.TypeOf((*MockSnippetRepo)(nil).TouchUsage), ctx, id)
}

// Update mocks base method.
func (m *MockSnippetRepo) Update(ctx context.Context, s *snippet_entity.Snippet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSnippetRepoMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSnippetRepo)(nil).Update), ctx, s)
}

// UpsertExtensionSeed mocks base method.
func (m *MockSnippetRepo) UpsertExtensionSeed(ctx context.Context, src *snippet_entity.Snippet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertExtensionSeed", ctx, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertExtensionSeed indicates an expected call of UpsertExtensionSeed.
func (mr *MockSnippetRepoMockRecorder) UpsertExtensionSeed(ctx, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertExtensionSeed", reflect.TypeOf((*MockSnippetRepo)(nil).UpsertExtensionSeed), ctx, src)
}
