// Code generated by MockGen. DO NOT EDIT.
// Source: host_key.go
//
// Generated by this command:
//
//	mockgen -source=host_key.go -destination=mock_host_key_repo/host_key.go -package=mock_host_key_repo
//

// Package mock_host_key_repo is a generated GoMock package.
package mock_host_key_repo

import (
	context "context"
	reflect "reflect"

	host_key_entity "github.com/opskat/opskat/internal/model/entity/host_key_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockHostKeyRepo is a mock of HostKeyRepo interface.
type MockHostKeyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHostKeyRepoMockRecorder
	isgomock struct{}
}

// MockHostKeyRepoMockRecorder is the mock recorder for MockHostKeyRepo.
type MockHostKeyRepoMockRecorder struct {
	mock *MockHostKeyRepo
}

// NewMockHostKeyRepo creates a new mock instance.
func NewMockHostKeyRepo(ctrl *gomock.Controller) *MockHostKeyRepo {
	mock := &MockHostKeyRepo{ctrl: ctrl}
	mock.recorder = &MockHostKeyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostKeyRepo) EXPECT() *MockHostKeyRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockHostKeyRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHostKeyRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHostKeyRepo)(nil).Delete), ctx, id)
}

// FindByHostPortKeyType mocks base method.
func (m *MockHostKeyRepo) FindByHostPortKeyType(ctx context.Context, host string, port int, keyType string) (*host_key_entity.HostKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHostPortKeyType", ctx, host, port, keyType)
	ret0, _ := ret[0].(*host_key_entity.HostKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHostPortKeyType indicates an expected call of FindByHostPortKeyType.
func (mr *MockHostKeyRepoMockRecorder) FindByHostPortKeyType(ctx, host, port, keyType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHostPortKeyType", reflect.TypeOf((*MockHostKeyRepo)(nil).FindByHostPortKeyType), ctx, host, port, keyType)
}

// List mocks base method.
func (m *MockHostKeyRepo) List(ctx context.Context) ([]*host_key_entity.HostKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*host_key_entity.HostKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHostKeyRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHostKeyRepo)(nil).List), ctx)
}

// UpdateLastSeen mocks base method.
func (m *MockHostKeyRepo) UpdateLastSeen(ctx context.Context, id, lastSeen int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSeen", ctx, id, lastSeen)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSeen indicates an expected call of UpdateLastSeen.
func (mr *MockHostKeyRepoMockRecorder) UpdateLastSeen(ctx, id, lastSeen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSeen", reflect.TypeOf((*MockHostKeyRepo)(nil).UpdateLastSeen), ctx, id, lastSeen)
}

// Upsert mocks base method.
func (m *MockHostKeyRepo) Upsert(ctx context.Context, key *host_key_entity.HostKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockHostKeyRepoMockRecorder) Upsert(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockHostKeyRepo)(nil).Upsert), ctx, key)
}
