// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function CreateAsset(arg1) {
  return window['go']['main']['App']['CreateAsset'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DetectLocalCLIs() {
  return window['go']['main']['App']['DetectLocalCLIs']();
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function ListAssets(arg1, arg2) {
  return window['go']['main']['App']['ListAssets'](arg1, arg2);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function LoadCredential(arg1) {
  return window['go']['main']['App']['LoadCredential'](arg1);
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function SaveCredential(arg1) {
  return window['go']['main']['App']['SaveCredential'](arg1);
}

export function SendAIMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAIMessage'](arg1, arg2);
}

export function SetAIProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAIProvider'](arg1, arg2, arg3, arg4);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function UpdateAsset(arg1) {
  return window['go']['main']['App']['UpdateAsset'](arg1);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['main']['App']['WriteSSH'](arg1, arg2);
}
