// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {asset_entity} from '../models';
import {group_entity} from '../models';
import {ai} from '../models';

export function ConnectSSH(arg1:main.SSHConnectRequest):Promise<string>;

export function CreateAsset(arg1:asset_entity.Asset):Promise<void>;

export function CreateGroup(arg1:group_entity.Group):Promise<void>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DetectLocalCLIs():Promise<Array<ai.CLIInfo>>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function ExportData():Promise<string>;

export function GetAsset(arg1:number):Promise<asset_entity.Asset>;

export function GetLanguage():Promise<string>;

export function ListAssets(arg1:string,arg2:number):Promise<Array<asset_entity.Asset>>;

export function ListGroups():Promise<Array<group_entity.Group>>;

export function LoadCredential(arg1:string):Promise<string>;

export function ResizeSSH(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveCredential(arg1:string):Promise<string>;

export function SendAIMessage(arg1:string,arg2:Array<ai.Message>):Promise<void>;

export function SetAIProvider(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function UpdateAsset(arg1:asset_entity.Asset):Promise<void>;

export function WriteSSH(arg1:string,arg2:string):Promise<void>;
